"""Add full order book depth tables

Revision ID: ad7907e30558
Revises:
Create Date: 2025-07-19 22:54:22.674048

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad7907e30558"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_book_snapshot",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "exchange_timestamp", sa.Numeric(precision=20, scale=6), nullable=False
        ),
        sa.Column("channel_uuid", sa.String(length=50), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_book_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            "idx_order_book_asset_timestamp",
            ["asset_id", "exchange_timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_order_book_snapshot_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_book_snapshot_channel_uuid"),
            ["channel_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_order_book_snapshot_exchange_timestamp"),
            ["exchange_timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_order_book_snapshot_id"), ["id"], unique=False
        )

    op.create_table(
        "order_book_level",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=36, scale=0), nullable=False),
        sa.Column("quantity_amount", sa.Numeric(precision=36, scale=0), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=36, scale=0), nullable=True),
        sa.Column("total_orders", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("side IN ('bid', 'ask')", name="chk_side_valid"),
        sa.CheckConstraint("price_amount >= 0", name="chk_price_non_negative"),
        sa.CheckConstraint("quantity_amount >= 0", name="chk_quantity_non_negative"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["order_book_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_book_level", schema=None) as batch_op:
        batch_op.create_index(
            "idx_order_book_level_side_price", ["side", "price_amount"], unique=False
        )
        batch_op.create_index(
            "idx_order_book_level_snapshot_side", ["snapshot_id", "side"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_book_level_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_book_level_side"), ["side"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_book_level_snapshot_id"), ["snapshot_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_book_level", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_book_level_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_order_book_level_side"))
        batch_op.drop_index(batch_op.f("ix_order_book_level_id"))
        batch_op.drop_index("idx_order_book_level_snapshot_side")
        batch_op.drop_index("idx_order_book_level_side_price")

    op.drop_table("order_book_level")
    with op.batch_alter_table("order_book_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_book_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_order_book_snapshot_exchange_timestamp"))
        batch_op.drop_index(batch_op.f("ix_order_book_snapshot_channel_uuid"))
        batch_op.drop_index(batch_op.f("ix_order_book_snapshot_asset_id"))
        batch_op.drop_index("idx_order_book_asset_timestamp")

    op.drop_table("order_book_snapshot")
    # ### end Alembic commands ###
