"""Add received_at timestamp column to order_book_level

Revision ID: cba25b240e75
Revises: ad7907e30558
Create Date: 2025-07-20 09:55:20.624851

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cba25b240e75"
down_revision: Union[str, Sequence[str], None] = "ad7907e30558"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_book_level", schema=None) as batch_op:
        batch_op.add_column(sa.Column("received_at", sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_order_book_level_received_at"), ["received_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_book_level", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_book_level_received_at"))
        batch_op.drop_column("received_at")

    # ### end Alembic commands ###
